# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import os
if os.path.exists("envtest.py"):
  import envtest

class TestDjangoBarberShopTesting():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_testCase001HomePageandFooterLinks(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(2560, 1392)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.TAG_NAME, 'body').send_keys(Keys.PAGE_DOWN)
    self.driver.find_element(By.TAG_NAME, 'body').send_keys(Keys.PAGE_DOWN)
    time.sleep(2)
    self.driver.find_element(By.ID, "facebook-link").click()
    self.vars["win9772"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win9772"])
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "twitter-link").click()
    self.vars["win2762"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win2762"])
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "insta-link").click()
    self.vars["win6994"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6994"])
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "youtube-link").click()
    self.vars["win1920"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win1920"])
    self.driver.switch_to.window(self.vars["root"])
  
  def test_testCase002Openaboutpageandseestaffinformation(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(2576, 1408)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "About").click()
    self.driver.find_element(By.TAG_NAME, 'body').send_keys(Keys.PAGE_DOWN)
    self.driver.find_element(By.TAG_NAME, 'body').send_keys(Keys.PAGE_DOWN)
    time.sleep(2)
  
  def test_testCase003RegisteranAccount(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(2576, 1408)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.LINK_TEXT, "sign up").click()
    self.driver.find_element(By.ID, "id_username").send_keys(os.environ.get("TEST_USER"))
    self.driver.find_element(By.ID, "id_first_name").send_keys(os.environ.get("TEST_USER_FIRST"))
    self.driver.find_element(By.ID, "id_last_name").send_keys(os.environ.get("TEST_USER_LAST"))
    self.driver.find_element(By.ID, "id_password1").send_keys(os.environ.get("TEST_USER_PASS"))
    self.driver.find_element(By.ID, "id_password2").send_keys(os.environ.get("TEST_USER_PASS"))
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.close()
  
  def test_testCase004Addandremoveuserasstaffmember(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(2576, 1408)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "id_login").send_keys(os.environ.get("ADMIN_USER"))
    self.driver.find_element(By.ID, "id_password").send_keys(os.environ.get("ADMIN_PASS"))
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "View Staff").click()
    self.driver.find_element(By.LINK_TEXT, "Add New").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .btn").click()
    self.driver.switch_to.frame(0)
    element = self.driver.find_element(By.CSS_SELECTOR, ".note-editable")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Test text</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.ID, "id_is_staff").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.TAG_NAME, 'body').send_keys(Keys.PAGE_DOWN)
    self.driver.find_element(By.TAG_NAME, 'body').send_keys(Keys.PAGE_DOWN)
    time.sleep(2)
    self.driver.find_element(By.ID, "id-edit-test_user").click()
    self.driver.switch_to.frame(0)
    element = self.driver.find_element(By.CSS_SELECTOR, ".note-editable")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>&nbsp;</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.ID, "id_is_staff").click()
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
  def test_testCase005CreateandEditaService(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(2576, 1408)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "id_login").send_keys(os.environ.get("ADMIN_USER"))
    self.driver.find_element(By.ID, "id_password").send_keys(os.environ.get("ADMIN_PASS"))
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Services").click()
    self.driver.find_element(By.LINK_TEXT, "Add New").click()
    self.driver.find_element(By.ID, "id_name").send_keys("Test service")
    self.driver.find_element(By.ID, "id_description").send_keys("Testing service")
    self.driver.find_element(By.ID, "id_price").send_keys("10")
    self.driver.find_element(By.ID, "id_is_combo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(8) .far").click()
    self.driver.find_element(By.ID, "id_price").send_keys("15")
    self.driver.find_element(By.ID, "id_is_combo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(8) .fa").click()
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "Confirm").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
  def test_testCase006UpdateShopInformation(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(2576, 1408)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "id_login").send_keys(os.environ.get("ADMIN_USER"))
    self.driver.find_element(By.ID, "id_password").send_keys(os.environ.get("ADMIN_PASS"))
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Shop Information").click()
    self.driver.find_element(By.ID, "id_postal_code").click()
    self.driver.find_element(By.ID, "id_postal_code").send_keys("T12T8H79")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
  def test_testCase007UpdateTradingDays(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(2576, 1408)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "id_login").send_keys(os.environ.get("ADMIN_USER"))
    self.driver.find_element(By.ID, "id_password").send_keys(os.environ.get("ADMIN_PASS"))
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Trading Days").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .fa").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Confirm").click()
    self.driver.find_element(By.LINK_TEXT, "Add New").click()
    self.driver.find_element(By.ID, "id_day").click()
    dropdown = self.driver.find_element(By.ID, "id_day")
    dropdown.find_element(By.XPATH, "//option[. = 'Sunday']").click()
    self.driver.find_element(By.ID, "id_open_time").click()
    self.driver.find_element(By.ID, "id_open_time").send_keys("00:00")
    self.driver.find_element(By.ID, "id_close_time").send_keys("14:00")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .far").click()
    self.driver.find_element(By.ID, "id_close_time").click()
    self.driver.find_element(By.ID, "id_close_time").send_keys("00:00")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
  def test_testCase008ManageBookings(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(2576, 1408)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "id_login").send_keys(os.environ.get("TEST_USER"))
    self.driver.find_element(By.ID, "id_password").send_keys(os.environ.get("TEST_USER_PASS"))
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Bookings").click()
    self.driver.find_element(By.LINK_TEXT, "Make booking").click()
    self.driver.find_element(By.ID, "id-check-availability").click()
    self.driver.find_element(By.ID, "id-save-booking").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .btn").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Confirm").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
  def test_testCase009UserProfileUpdate(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(2576, 1408)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "id_login").send_keys(os.environ.get("TEST_USER"))
    self.driver.find_element(By.ID, "id_password").send_keys(os.environ.get("TEST_USER_PASS"))
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Edit").click()
    self.driver.find_element(By.ID, "id_email").send_keys(os.environ.get("TEST_USER_MAIL"))
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
