# Generated by Django 4.2.10 on 2024-03-05 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
