# Generated by Django 4.2.10 on 2024-03-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_service_price_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
