# Generated by Django 4.2.10 on 2024-03-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_alter_service_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
    ]
