# Generated by Django 4.2.10 on 2024-03-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_description_user_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffUser',
        ),
    ]
