# Generated by Django 4.2.10 on 2024-03-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='address1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='info',
            name='address2',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
