# Generated by Django 4.2.10 on 2024-03-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tradingdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdays',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True),
        ),
    ]
