# Generated by Django 4.2.10 on 2024-03-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_tradingdays_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='TradingDays',
        ),
    ]
